// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6mxUlKLMfyGoOlnLz_2WGSImQQHP1pzQ',
    appId: '1:890809865754:android:8a1a1d06ba8d166499e3a3',
    messagingSenderId: '890809865754',
    projectId: 'pet-health-tracker-2eed5',
    storageBucket: 'pet-health-tracker-2eed5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkfdmkChVqn3SEY_l1ntnHMv7VkynEOVY',
    appId: '1:890809865754:ios:adde1a8a210dfbd399e3a3',
    messagingSenderId: '890809865754',
    projectId: 'pet-health-tracker-2eed5',
    storageBucket: 'pet-health-tracker-2eed5.firebasestorage.app',
    androidClientId: '890809865754-la7779jbic820ptbtnic5lrts66dj0n0.apps.googleusercontent.com',
    iosClientId: '890809865754-90ue3j5p8d9p84sgdhbbld3nf88sndca.apps.googleusercontent.com',
    iosBundleId: 'com.pootzandboogie.petHealthTracker',
  );
}
