#!/usr/bin/env bash
# Every check a commit must pass before it ships. CI and the pre-push hooks run
# this same script, so passing locally means passing in CI.
set -euo pipefail
cd "$(dirname "$0")/.."

echo '==> format'
# firebase_options.dart is generated by flutterfire, so it's left as generated.
find lib test -name '*.dart' ! -name firebase_options.dart -print0 \
  | xargs -0 dart format --output=none --set-exit-if-changed

echo '==> analyze'
flutter analyze --fatal-infos

echo '==> test'
flutter test --coverage
